name = "{{project-name}}"
type = "javascript"
webpack_config = "webpack.config.js"

account_id = ""
workers_dev = true
route = ""
zone_id = ""

[wasm_modules]
WASM_MODULE = "worker/module.wasm"

[build]
command = "npm run build"

[build.upload]
format = "service-worker"